@startuml System Sequence Diagram for Client's "Register as Client" Use Case
title System Sequence Diagram for Client's "Register as Client" Use Case
skinparam sequenceMessageAlign center 

actor "<u>:User" as user
participant "<u>:System" as system

user -> system : enterRegisterClientCommandId()
system --> user : requestFirstName
user -> system : enterFirstName(firstName)
system --> user : requestLastName
user -> system : enterLastName(lastName)
system --> user : requestEmail
user -> system : enterEmail(email)
system --> user : requestPassword
user -> system : enterPassword(password)
system --> user : requestPhoneNumber
user -> system : enterPhoneNumber(phoneNumber)
system -> system : client := getByEmail(email)
alt client does not already exist
    system -> system : createClient(firstName, lastName, email, password, phoneNumber)
    alt successful creation
        system --> user : displaySuccess
    else creation failure
        system --> user : displayError
    end
else client exists
    system --> user : displayError
end

@enduml