@startuml
actor "<u>:Client" as client
participant "<u>:Terminal" as terminal
participant "<u>:AddDependentCommand" as command
participant "<u>:ChildCollection" as childCollection
participant "DatabaseManager" as databaseManager
participant "<u>child:Child" as childObj

client -> terminal : enterAddDependentCommandId()
terminal -> command : execute()
command -> command : requestFirstName()
client -> command : enterFirstName(firstName)
command -> command : requestLastName()
client -> command : enterLastName(lastName)
command -> command : requestDateOfBirth()
client -> command : enterDateOfBirth(dateOfBirth)
command -> childCollection : validateChild(clientId, firstName, lastName, dateOfBirth)
childCollection -> databaseManager : getConnection()
databaseManager --> childCollection : connection
alt child exists
    childCollection --> command : childExistsError
else child does not exist
    command -> childCollection : createChild(clientId, firstName, lastName, dateOfBirth)
    childCollection -> childObj ** : new Child(firstName, lastName, dateOfBirth, clientId)
    childObj --> childCollection : newChild
    childCollection -> childCollection : childId := add(newChild)
    childCollection -> databaseManager : getConnection()
    databaseManager --> childCollection : connection
    alt successful creation
        childCollection -> client : addChild(childId)
    else creation failed
        childCollection --> command : null
    end
end
@enduml