@startuml
actor "User" as user
participant "<u>:Terminal" as terminal
participant "<u>:RegisterInstructorCommand" as command
participant "<u>:InstructorCollection" as instructorCollection
participant "DatabaseManager" as databaseManager
participant "<u>Instructor:Instructor" as newInstructorObj

user -> terminal : enterRegisterInstructorCommandId()
terminal -> command : execute()
command -> command : requestFirstName()
user -> command : enterFirstName(firstName)
command -> command : requestLastName()
user -> command : enterLastName(lastName)
command -> command : requestEmail()
user -> command : enterEmail(email)
command -> command : requestPassword()
user -> command : enterPassword(password)

command -> instructorCollection : getByEmail(email)
instructorCollection -> databaseManager : getConnection()
databaseManager --> instructorCollection : connection
instructorCollection --> command : instructor

alt no existing instructor found
    command -> instructorCollection : createInstructor(firstName, lastName, email, password)
    instructorCollection -> newInstructorObj ** : new Instructor(firstName, lastName, email, password)
    newInstructorObj --> instructorCollection : newInstructorObj
    instructorCollection -> instructorCollection : add(newInstructorObj)
    instructorCollection -> databaseManager : getConnection()
    databaseManager --> instructorCollection : connection
    alt successful creation
        instructorCollection --> command : True
    else creation failure
        instructorCollection --> command : False
    end
end
@enduml
