@startuml


title View Edit Offerings
skinparam sequenceMessageAlignment center


actor "i:<u>Instructor" as i
participant ":<u>Terminal" as Terminal
participant "ConsoleUtils" as cUtils
participant "LessonCollection" as LessonCollection
collections "instructorLessons:<u>Lesson" as instructorLessons
participant "selectedLesson:<u>Lesson" as selectedLesson


i -> Terminal : viewEditOfferings(i)
Terminal -> LessonCollection : getByInstructorId(i.getId())
LessonCollection -> instructorLessons ** : create()
LessonCollection --> Terminal: instructorLessons

loop
  Terminal -> cUtils : printTable(instructorLessons, unwantedPropertiesToDisplay)
  i -> Terminal : selectLesson(lessonId)
  Terminal -> instructorLessons : find(lessonId)
  
  alt Lesson Found
    instructorLessons --> Terminal : selectedLesson
    
    alt Unassign from Lesson
      Terminal -> selectedLesson : setAssignedInstructorId(null)
      Terminal -> i : removeLesson(lessonId)
    end
  
  else Lesson not Found
    Terminal --> i : failure
  end
end

i -> Terminal : exitViewEditOfferings()


@enduml