@startuml Interaction Diagram for Admin's "Delete User Account" Use Case
title Interaction Diagram for Admin's "Delete User Account" Use Case
skinparam sequenceMessageAlignment center

actor "<u>:Administrator" as admin
participant "<u>:Terminal" as terminal
participant "<u>:DeleteUserCommand" as command
participant "ConsoleUtils" as consoleUtils
participant "InstructorCollection" as instructorCollection
participant "ClientCollection" as clientCollection
participant "DatabaseManager" as databaseManager

admin -> terminal : enterDeleteUserAccountCommandId()
terminal -> command : execute()
command -> command : requestUserType(s)
admin -> command : enterUserType(userType)
alt userType == UserType.CLIENT
    command -> clientCollection : getClients()
    clientCollection -> databaseManager : getConnection()
    databaseManager --> clientCollection : connection
    clientCollection --> command : clients
    command -> consoleUtils : printTable(clients, nonDisplayProperties)
    command -> command : requestUserId()
    admin -> command : enterUserId(userId)
    command -> command : confirmDeletion()
    admin -> command : confirmDeletion(confirmation)
    command -> clientCollection : delete(userId)
    clientCollection -> databaseManager : getConnection()
    databaseManager --> clientCollection : connection
    alt successful deletion 
        clientCollection --> command : True
    else deletion failure
        clientCollection --> command : False
    end
else userType == UserType.INSTRUCTOR
    command -> instructorCollection : getInstructors()
    instructorCollection -> databaseManager : getConnection()
    databaseManager --> instructorCollection : connection
    instructorCollection --> command : instructors
    command -> consoleUtils : printTable(instructors, nonDisplayProperties)
    command -> command : requestUserId()
    admin -> command : enterUserId(userId)
    command -> command : confirmDeletion()
    admin -> command : confirmDeletion(deletion)
    command -> instructorCollection : delete(userId)
    instructorCollection -> databaseManager : getConnection()
    databaseManager --> instructorCollection : connection
    alt successful deletion 
        instructorCollection --> command : success
        command --> terminal : displaySuccess
        terminal --> admin : displaySuccess
    else deletion failure
        instructorCollection --> command : failure
        command --> terminal : displayError
        terminal --> admin : displayError
    end
end
@enduml